//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Betburger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Betburger.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[&quot;MESSAGE\nid:/api/en-GB/events/{0}.
        /// </summary>
        internal static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;CONNECT\nprotocol-version:1.3\naccept-version:1.1,1.0\nheart-beat:10000,10000\n\n\u0000&quot;].
        /// </summary>
        internal static string Param1 {
            get {
                return ResourceManager.GetString("Param1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;UNSUBSCRIBE\nid:/api/en-GB/event-groups/{0}\n\n\u0000&quot;].
        /// </summary>
        internal static string Param10 {
            get {
                return ResourceManager.GetString("Param10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;UNSUBSCRIBE\nid:/api/event-group-list/LIVE\n\n\u0000&quot;].
        /// </summary>
        internal static string Param11 {
            get {
                return ResourceManager.GetString("Param11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;UNSUBSCRIBE\nid:/api/event-group-list/UPCOMING\n\n\u0000&quot;].
        /// </summary>
        internal static string Param12 {
            get {
                return ResourceManager.GetString("Param12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/user/request-response\ndestination:/user/request-response\n\n\u0000&quot;].
        /// </summary>
        internal static string Param2 {
            get {
                return ResourceManager.GetString("Param2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/user/error\ndestination:/user/error\n\n\u0000&quot;].
        /// </summary>
        internal static string Param3 {
            get {
                return ResourceManager.GetString("Param3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/api/event-group-list/LIVE\ndestination:/api/event-group-list/LIVE\n\n\u0000&quot;].
        /// </summary>
        internal static string Param4 {
            get {
                return ResourceManager.GetString("Param4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/api/event-group-list/UPCOMING\ndestination:/api/event-group-list/UPCOMING\n\n\u0000&quot;].
        /// </summary>
        internal static string Param5 {
            get {
                return ResourceManager.GetString("Param5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/api/en-GB/event-groups/{0}\ndestination:/api/en-GB/event-groups/{1}\n\n\u0000&quot;].
        /// </summary>
        internal static string Param6 {
            get {
                return ResourceManager.GetString("Param6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/api/en-GB/event-groups/{0}\ndestination:/api/en-GB/event-groups/{1}\n\n\u0000&quot;].
        /// </summary>
        internal static string Param7 {
            get {
                return ResourceManager.GetString("Param7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [&quot;SUBSCRIBE\nid:/api/en-GB/events/{0}\ndestination:/api/en-GB/events/{1}\n\n\u0000&quot;].
        /// </summary>
        internal static string Param8 {
            get {
                return ResourceManager.GetString("Param8", resourceCulture);
            }
        }
    }
}
